ToDoList.Web/Models/ErrorViewModel.cs
namespace ToDoList.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoList.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoList.Web.Models;

namespace ToDoList.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoList.Web/Controllers/NoteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ToDoList.Core.DTOs;
using ToDoList.Core.Model;
using ToDoList.Web.Services;

namespace ToDoList.Web.Controllers
{
    public class NoteController : Controller
    {
        private readonly UserApiService _userApiService;
        private readonly NoteApiService _noteApiService;

        public NoteController(NoteApiService noteApiService, UserApiService userApiService)
        {
            _noteApiService = noteApiService;
            _userApiService = userApiService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _noteApiService.GetAllNoteWithUsers());
        }
        public async Task<IActionResult> Save()
        {
            var users= await _userApiService.GetAllAsync();
            ViewBag.users = new SelectList(users, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Save(NoteDto noteDto)
        {
            if (ModelState.IsValid)
            {

                await _noteApiService.SaveAsync(noteDto);
                return RedirectToAction(nameof(Index));
            }
            var users = await _userApiService.GetAllAsync();
            ViewBag.users = new SelectList(users, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            var notes= await _noteApiService.GetByIdAsync(id);
            var users = await _userApiService.GetAllAsync();
            ViewBag.users = new SelectList(users, "Id", "Name");
            return View(notes);
        }
        [HttpPost]
        public async Task<IActionResult> Update(NoteDto noteDto)
        {
            if (ModelState.IsValid)
            {
                await _noteApiService.UpdateAsync(noteDto);
                return RedirectToAction(nameof(Index));
            }
            var users = await _userApiService.GetAllAsync();
            ViewBag.users = new SelectList(users, "Id", "Name");
            return View(noteDto);

        }

        public async Task<IActionResult> Remove(int id)
        {
            await _noteApiService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ToDoList.Web/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ToDoList.Core.DTOs;
using ToDoList.Core.Model;
using ToDoList.Core.Services;
using ToDoList.Service.Services;
using ToDoList.Web.Services;

namespace ToDoList.Web.Controllers
{
    public class UserController : Controller
    {

        private readonly UserApiService _userApiService;
        private readonly UserRoleApiService _userRoleApiService;

        public UserController(UserApiService userApiService, UserRoleApiService userRoleApiService)
        {
            _userApiService = userApiService;
            
            _userRoleApiService = userRoleApiService;
        }
        public async Task<IActionResult> Index()
        {
            var userrole = await _userRoleApiService.GetAllAsync();
            var user = await _userApiService.GetUserWithUserRoleAsync();
            ViewBag.userrole = new SelectList(userrole, "Id", "Name");
            return View(user);
        }

        public async Task<IActionResult> Save()
        {
            var userrole = await _userRoleApiService.GetAllAsync();
            ViewBag.userrole = new SelectList(userrole, "Id", "Name");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Save(UserDto userDto)
        {
            if (ModelState.IsValid)
            {
                await _userApiService.SaveAsync(userDto); 
                return RedirectToAction(nameof(Index));
            }
            var userrole = await _userRoleApiService.GetAllAsync();
            ViewBag.userrole = new SelectList(userrole, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> Update(int id)
        {
            var user = _userApiService.GetByIdAsync(id);
            var userrole = await _userRoleApiService.GetAllAsync();
            ViewBag.userrole = new SelectList(userrole, "Id", "Name");
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> Update(UserDto userDto)
        {

            if (ModelState.IsValid)
            {

                await _userApiService.UpdateAsync(userDto);
                return RedirectToAction(nameof(Index));

            }
            var userrole = await _userRoleApiService.GetAllAsync();
            ViewBag.userrole = new SelectList(userrole, "Id", "Name");

            return View(userDto);
        }

        public async Task<IActionResult> Remove(int id)
        {          
            await _userApiService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ToDoList.Web/Controllers/UserRoleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ToDoList.Core.DTOs;
using ToDoList.Core.Model;
using ToDoList.Core.Services;
using ToDoList.Web.Services;

namespace ToDoList.Web.Controllers
{
    public class UserRoleController : Controller
    {
        private readonly UserRoleApiService _userRoleApiService;

        public UserRoleController(UserRoleApiService userRoleApiService)
        {
            _userRoleApiService = userRoleApiService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _userRoleApiService.GetAllAsync());
        }

        public async Task<IActionResult> Save()
        {          
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Save(UserRoleDto userRoleDto)
        {

            if (ModelState.IsValid)
            {
                await _userRoleApiService.SaveAsync(userRoleDto);
                return RedirectToAction(nameof(Index));
            }       
            return View(userRoleDto);
        }

        public async Task<IActionResult> Update(int id)
        {
            var userrole = await _userRoleApiService.GetByIdAsync(id);
            return View(userrole);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UserRoleDto userRoleDto)
        {

            if (ModelState.IsValid)
            {
                await _userRoleApiService.UpdateAsync(userRoleDto);
                return RedirectToAction(nameof(Index));
            }
           
            return View(userRoleDto);
        }


        public async Task<IActionResult> Remove(int id)
        {
            await _userRoleApiService.RemoveAsync(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

ToDoList.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDoList.Web/Views/Note/Index.cshtml
@using ToDoList.Core.Model
@{
    ViewData["Title"] = "Index";
}
@model List<NoteWithUserDto>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>ID</td>
                <td>Description</td>         
                <td>UserId</td>
                <td>Actions</td>

            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Description</td>
                    <td>@item.UserId</td>                    
                    <td>
                        <a class="btn btn-warning" asp-controller="Note" asp-action="Update" asp-route-id="@item.Id">Update</a>                                       
                        <a class="btn btn-danger" asp-controller="Note" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    
    </table>
<a class="btn btn-info" asp-controller="Note" asp-action="Save">Yeni Not Ekle</a>

ToDoList.Web/Views/Note/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model NoteDto
<h1>Save Note</h1>

<div class="row">
    <div class="col-md-6">

        <form asp-action="Save" method="post" asp-controller="Note">
           
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserId"></label>
                <select asp-for="UserId" asp-items="ViewBag.users" class="form-control"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

ToDoList.Web/Views/Note/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

@model NoteDto
<h1>Update Note</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Update" method="post" asp-controller="Note">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

             <div class="form-group">
                <label asp-for="UserId"></label>
                <select asp-for="UserId" asp-items="ViewBag.users" class="form-control"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div>
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ToDoList.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserRole" asp-action="Index">UserRole</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">Note</a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDoList.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoList.Web/Views/User/Index.cshtml
@using ToDoList.Core.Model

@{
    ViewData["Title"] = "Index";
}
@model List<UserWithUserRoleDto>
<table class="table table-striped">
    <thead>
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Surname</td>
            <td>Email</td>
            <td>Password</td>
            <td>UserRole</td>
            <td>Actions</td>

        </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Surname</td>
                <td>@item.Email</td>
                <td>@item.Password</td>
                <td>
                    <input asp-for="@item.UserRole.Name" asp-items="ViewBag.userrole" class="form-control" />
                </td>
                <td>
                 <a class="btn btn-warning" asp-controller="User" asp-action="Update" asp-route-id="@item.Id">Update</a>
                 <a class="btn btn-danger" asp-controller="User" asp-action="Remove" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a href="/User/Save" class="btn btn-info">Yeni User Ekle</a>

ToDoList.Web/Views/User/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model UserDto
<h1>Save User</h1>

<div class="row">
    <div class="col-md-6">

        <form asp-action="Save" method="post" asp-controller="User">
            
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserRoleId"></label>
                <select asp-for="UserRoleId" asp-items="ViewBag.userrole" class="form-control"></select>
                <span asp-validation-for="UserRoleId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>

</div>

ToDoList.Web/Views/User/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
@model UserDto
<h1>Update User</h1>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Update" method="post" asp-controller="User">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Surname"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserRoleId"></label>              
                <select asp-for="UserRoleId" asp-items="ViewBag.userrole" class="form-control" />
                <span asp-validation-for="UserRoleId" class="text-danger"></span>
            </div>
            <div>
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ToDoList.Web/Views/UserRole/Index.cshtml
@using ToDoList.Core.Model

@{
    ViewData["Title"] = "Index";
}
@model List<UserRoleDto>
 <table class="table table-striped">
     <thead>
         <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Update</td>
            <td>Delete</td>

         </tr>
         
     </thead>
     <tbody>
         @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                    <a class="btn btn-warning" asp-controller="UserRole" asp-action="Update" asp-route-id="@item.Id">Update</a>
                </td>
                <td> 
                    <a class="btn btn-danger" asp-controller="UserRole" asp-action="Remove" asp-route-id="@item.Id">Delete</a> 
                 </td>
            </tr>
        }
     </tbody>
 </table>
<a href="/UserRole/Save" class="btn btn-info">Yeni UserRole Ekle</a>

ToDoList.Web/Views/UserRole/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
@model UserRoleDto
<h1>Save UserRole</h1>

<div class="row">
    <div class="col-md-6">

        <form asp-action="Save" method="post" asp-controller="UserRole">

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

ToDoList.Web/Views/UserRole/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
@model UserRoleDto
<h1>Update UserRole</h1>

<div class="row">
    <div class="col-md-6">

        <form asp-action="Update" method="post" asp-controller="UserRole">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>